# Generated by Django 4.2.19 on 2025-03-09 16:53

import ckeditor_uploader.fields
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('client_name', models.CharField(max_length=500)),
                ('project_link', models.URLField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('thumbnail_image', models.ImageField(upload_to=projects.models.rename_file)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=projects.models.rename_file)),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_keywords', models.TextField(blank=True, max_length=500, null=True)),
                ('canonical_tag', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='canonical_tag',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title',
        ),
    ]
