# Generated by Django 4.2.19 on 2025-03-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_seo_category_canonical_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsimages',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.projects'),
        ),
    ]
