# Generated by Django 4.2.19 on 2025-03-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectsimages_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.category'),
        ),
    ]
