# Generated by Django 4.2.19 on 2025-03-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projects_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project',
            new_name='category',
        ),
    ]
