# Generated by Django 3.2.12 on 2025-03-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_name_category_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProjectsCategory',
        ),
    ]
