# Generated by Django 3.2.12 on 2025-03-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_trending',
        ),
    ]
