# Generated by Django 3.2.12 on 2025-03-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
