# Generated by Django 3.2.12 on 2025-03-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='trending',
        ),
    ]
