# Generated by Django 4.2.19 on 2025-03-09 04:42

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('alternative_phone', models.CharField(max_length=15, null=True)),
                ('google_map_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('favicon_icon', models.ImageField(null=True, upload_to=master.models.rename_file)),
                ('logo_icon', models.ImageField(null=True, upload_to=master.models.rename_file)),
                ('address', models.TextField(blank=True, null=True)),
                ('footer_description', models.TextField(blank=True, null=True)),
                ('footer_image', models.ImageField(null=True, upload_to=master.models.rename_file)),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('gmail_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Send Mail)')),
                ('password', models.CharField(blank=True, max_length=350, verbose_name='Password (Send Mail)')),
                ('office_hours', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('Home', 'Home'), ('About', 'About'), ('Blogs', 'Blogs'), ('FAQ', 'FAQ'), ('Pricing', 'Pricing'), ('Contact', 'Contact')], max_length=20, null=True)),
                ('meta_title', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_keywords', models.TextField(blank=True, max_length=500, null=True)),
                ('canonical_tag', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube'), ('Telegram', 'Telegram'), ('Whatsapp', 'Whatsapp'), ('Threads', 'Threads')], max_length=100, null=True)),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
