# Generated by Django 4.2.19 on 2025-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('Blogs', 'Blogs'), ('Projects', 'Projects')], max_length=150, null=True),
        ),
    ]
